services:
  mediamtx:
    image: bluenviron/mediamtx:1-ffmpeg
    container_name: mediamtx-ffmpeg-Tao-Nan
    networks:
      - app-net
    restart: unless-stopped
    ports:
      - "1935:1935" # RTMP
      - "8555:8554" # RTSP
      - "8888:8888" # HLS Playback
      - "8889:8889" # WebRTC
      - "8889:8889/udp" # WebRTC Media (The video streams)
      - "9997:9997" # API
      - "8189:8189/udp" #udps
    volumes:
      - ./Ingestion-Gateway/mediamtx/mediamtx.yml:/mediamtx.yml

  ai-worker:
    build:
      context: . # Builds from the root directory
      dockerfile: Dockerfile
    container_name: ai_worker_tao_nan
    networks:
      - app-net
    restart: unless-stopped
    depends_on:
      - mediamtx

    env_file:
      - ./Ai-Worker/.env

    # CRITICAL: This grants Docker access to your NVIDIA RTX 4050
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  app-net:
    driver: bridge
